FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

FROM node:20

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/src ./src

COPY --from=builder /app/prisma ./prisma

COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/.env ./.env

EXPOSE 9532

CMD ["node", "src/server.js"]